---

apiVersion: v1

kind: Service

metadata:
  name: javawebapp-service

spec:
  type: LoadBalancer

  selector:
    app: java-web-app
    color: blue

  ports:
  - port: 80
    targetPort: 8080

...
