---

apiVersion: v1

kind: Service

metadata:
  name: bluegreen-service

spec:
  type: LoadBalancer

  selector:
    app: bluegreen-app
    color: blue

  ports:
  - port: 80
    targetPort: 8080

...
